//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subjoin.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VenueCategory
    {
        public VenueCategory()
        {
            this.Children = new HashSet<VenueCategory>();
            this.Venues = new HashSet<Venue>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentId { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual ICollection<VenueCategory> Children { get; set; }
        public virtual VenueCategory Parent { get; set; }
        public virtual ICollection<Venue> Venues { get; set; }
    }
}
